// Mock API endpoint for updating essay group assignments
// TODO: Replace this with actual database integration

export default defineEventHandler(async (event) => {
  const method = event.method;
  const essayId = parseInt(event.context.params?.id || "0");

  if (!essayId) {
    throw createError({
      statusCode: 400,
      statusMessage: "Essay ID is required",
    });
  }

  // Mock essays from essay.json
  const mockEssays = [
    {
      id: 1,
      question:
        "Accoording TLI ( Temporary Local Instruction ) Jakarta ACC and MEDAN APP , when Jakarta ACC shall transfer surveillance identification to Medan East TMA within surveillance coverage accepting unit …",
      answer:
        "Jakarta ACC shall transfer surveillance identification to Medan East TMA within surveillance coverage accepting unit before 300 nm until 150 nm of DES VOR",
      image: "",
      value: 4,
    },
    {
      id: 2,
      question:
        "Accoording TLI ( Temporary Local Instruction ) Jakarta ACC and MEDAN APP, when Jakarta ACC shall transfer surveillance identification to Medan West TMA within surveillance coverage accepting unit ..",
      answer:
        "Jakarta ACC shall transfer surveillance identification to Medan west TMA within surveillance coverage accepting unit before 200 nm until 100 nm of BAC VOR.",
      image: "",
      value: 4,
    },
    {
      id: 3,
      question:
        "According TLI JKT ACC- MDN APP, Exemption transfer surveillance identification and using Approval request for aircraft Inbound Outbound WIMM & WITT from/ to West & North , mention the routes ?",
      answer: "P574, M300, N563, P756, L762",
      image: "",
      value: 3,
    },
    {
      id: 4,
      question:
        "when Jakarta ACC shall transfer surveillance identification to Pontianak APP",
      answer:
        "within surveillance coverage accepting unit between 180 nm until 130 nm of PNK VOR",
      image: "",
      value: 5,
    },
    {
      id: 5,
      question: "Mention 3 adjacent units of Upper Palembang vertically",
      answer:
        "1. Lower North 2. Palembang APP-TMA 3. Jakarta FIC Jakarta Sector",
      image: "",
      value: 3,
    },
    {
      id: 6,
      question:
        "What is the code on Field 10a of Flight Plan to be filled if the aircraft is equipped with CPDLC …....... and what is the LOGON ADS-C/CPDLC in the Jakarta FIR…..",
      answer: "Code J1, and LOGON ADS-C/CPDLC in Jakarta FIR is WIII",
      image: "",
      value: 3,
    },
  ];

  // Available question groups
  const questionGroups = [
    {
      id: 1,
      label: "PENDEK (ACP)",
      group: "PENDEK",
      rating: "ACP",
    },
    {
      id: 2,
      label: "PANJANG (ACP)",
      group: "PANJANG",
      rating: "ACP",
    },
    {
      id: 11,
      label: "PENDEK (ACS)",
      group: "PENDEK",
      rating: "ACS",
    },
    {
      id: 12,
      label: "PANJANG (ACS)",
      group: "PANJANG",
      rating: "ACS",
    },
  ];

  // POST - Create essay group assignment
  if (method === "POST") {
    const body = await readBody(event);
    // console.log(body);

    // Validate input - simple structure with essayId and questionGroupId
    if (!body.essayId) {
      throw createError({
        statusCode: 400,
        statusMessage: "essayId is required",
      });
    }

    if (!body.questionGroupId) {
      throw createError({
        statusCode: 400,
        statusMessage: "questionGroupId is required",
      });
    }

    // Find essay
    const essay = mockEssays.find((e) => e.id === essayId);

    if (!essay) {
      throw createError({
        statusCode: 404,
        statusMessage: "Essay not found",
      });
    }

    // Find question group
    const questionGroup = questionGroups.find(
      (qg) => qg.id === body.questionGroupId,
    );

    if (!questionGroup) {
      throw createError({
        statusCode: 404,
        statusMessage: "Question group not found",
      });
    }

    // Create single assignment entry (like essayGroup.json structure)
    const newAssignment = {
      id: Date.now(), // In production, this would be auto-generated by DB
      sector: {
        id: body.sectorId || 1,
        sector: body.sector || "WEST",
      },
      essay: {
        id: essay.id,
        question: essay.question,
        answer: essay.answer,
        image: essay.image,
        value: essay.value,
      },
      questionGroup: {
        id: body.questionGroupId,
        kindOfQuestion: { id: 1, question: "ESSAY" },
        group: questionGroup.group,
        rating: { id: questionGroup.id, rating: questionGroup.rating },
      },
    };

    // In production, save to database here
    // await db.essayGroupAssignments.create(newAssignment)

    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 300));

    return {
      success: true,
      data: newAssignment,
      message: "Essay group assignment created successfully",
    };
  }

  // PUT - Update essay group assignment
  if (method === "PUT") {
    const body = await readBody(event);

    // Validate input
    if (!body.questionGroupId) {
      throw createError({
        statusCode: 400,
        statusMessage: "Question group ID is required",
      });
    }

    if (
      !body.sectors ||
      !Array.isArray(body.sectors) ||
      body.sectors.length === 0
    ) {
      throw createError({
        statusCode: 400,
        statusMessage: "At least one sector must be selected",
      });
    }

    // Find essay
    const essay = mockEssays.find((e) => e.id === essayId);

    if (!essay) {
      throw createError({
        statusCode: 404,
        statusMessage: "Essay not found",
      });
    }

    // Find question group
    const questionGroup = questionGroups.find(
      (qg) => qg.id === body.questionGroupId,
    );

    if (!questionGroup) {
      throw createError({
        statusCode: 404,
        statusMessage: "Question group not found",
      });
    }

    // Create assignment
    const assignment = {
      essayId: essayId,
      questionGroupId: body.questionGroupId,
      questionGroup: questionGroup.group,
      rating: questionGroup.rating,
      sectors: body.sectors,
    };

    // In production, save to database here
    // await db.essayGroupAssignments.upsert({
    //   where: { essayId_questionGroupId: { essayId, questionGroupId } },
    //   update: { sectors: body.sectors },
    //   create: assignment
    // })

    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 300));

    return {
      success: true,
      data: assignment,
      message: "Essay group assignment updated successfully",
    };
  }

  // Method not allowed
  throw createError({
    statusCode: 405,
    statusMessage: "Method not allowed",
  });
});
